sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=trunk WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=1

install:
  - composer self-update --no-interaction
  - composer install --no-interaction --prefer-dist

before_script:
    - source bin/travis.before_script.sh

script:
    - bin/travis.script.sh
    - phpunit